name: hasql-postgres
root: ~/loadtest
pre_window: ulimit -n 1048576
windows:
  - tester:
      layout: main-vertical
      panes:
        - POSTGRES="host=localhost port=6432 user=$USER password=$PGPASSWORD dbname=$USER" ./bin/testing-service
        - |
          sleep 1
          curl http://localhost:9000/hasql/item?th=false&transaction=true&release=false
          wrk -d 60 -t 400 -c 2000 http://localhost:9000/hasql/collection?th=false&transaction=true&release=false&list=false
          wrk -d 60 http://localhost:9000/hasql/item?th=false&transaction=true&release=false
  - user:
      panes:
        - POSTGRES="host=localhost port=6432 user=$USER password=$PGPASSWORD dbname=$USER" ./bin/testing-service -p 9001
        - while true; do time curl http://localhost:9001/hasql/item?th=false&transaction=true&release=false ; sleep 1; done
  - pooler:
      - cd odyssey; make console_run
