name: hasql-postgres
root: ~/loadtest
on_project_start:
  - ulimit -n 1048576
windows:
  - tester:
      layout: main-vertical
      panes:
        - POSTGRES="host=localhost port=6432 user=$USER password=$PGPASSWORD dbname=$USER" ./bin/testing-service
        - |
          sleep 1
          curl http://localhost:9000/hasql/item?th=false&transaction=true&release=false
          wrk -d 5 -t 400 -c 2000 http://localhost:9000/hasql/collection?th=false&transaction=true&release=false&list=false
          wrk -d 5 http://localhost:9000/hasql/item?th=false&transaction=true&release=false
  - pooler:
      - cd odyssey; make console_run
