name: hasql-loadtest-template

ghc-options:
  - -Wall

library:
  source-dirs:
    - src

executables:
  testing-service:
    main: exe/Main.hs
    dependencies:
      - hasql-loadtest-template
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N

dependencies:
  - base
  - servant
  - servant-server
  - hasql
  - hasql-th
  - hasql-transaction
  - text
  - bytestring
  - vector
  - transformers
  - aeson
  - wai
  - wai-extra
  - warp
